# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIStoreKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default=uuid.UUID('2e82d648-c207-11e7-a6f7-dc0ea15fbe37'), max_length=36, verbose_name='AppKey')),
                ('app_key', models.CharField(max_length=32, verbose_name='AppKey')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API商城KEY',
                'verbose_name_plural': 'API商城KEY',
            },
        ),
        migrations.CreateModel(
            name='AppKeySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(max_length=32, verbose_name='AppKey')),
                ('api_type', models.IntegerField(choices=[(1, '北京快乐8')], verbose_name='类型')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配置APP-KEY',
                'verbose_name_plural': '配置APP-KEY',
            },
        ),
    ]
