# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BJkeNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=16, verbose_name='期号')),
                ('nums', models.CharField(max_length=128, verbose_name='开奖号码')),
                ('frisbee', models.IntegerField(verbose_name='飞盘')),
                ('pc_nums', models.CharField(max_length=23, verbose_name='PC28号码')),
                ('pc_sum', models.IntegerField(verbose_name='PC28值')),
                ('date', models.DateTimeField(verbose_name='开奖时间')),
                ('create_date', models.DateTimeField(verbose_name='获取时间')),
            ],
            options={
                'ordering': ['-issue'],
                'verbose_name': '北京快乐8',
                'verbose_name_plural': '北京快乐8',
            },
        ),
    ]
