# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryMiss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_type', models.IntegerField(choices=[(8601001, '北京快乐8')], verbose_name='类型')),
                ('issue', models.CharField(max_length=16, verbose_name='期号')),
                ('is_insert', models.BooleanField(default=False, verbose_name='插入')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '开奖遗漏期',
                'ordering': ['lottery_type', '-issue'],
                'verbose_name': '开奖遗漏期',
            },
        ),
        migrations.AddField(
            model_name='bjkeno',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='bjkeno',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='获取时间'),
        ),
    ]
